### PR TITLE
Unset server properties after use to prevent memory leaks.

### PR DESCRIPTION
**Pull request by PeterPlucinski**

### CODE REVIEW

**Comment by navarr** [comment]
Thank you for this.  I'll take a look within the next couple of days (I'm planning to right now - but if something comes up I want my bases covered)

**Comment by PeterPlucinski** [comment]
Great, no problem.

**Comment by navarr** [comment]
I've merged in your changes - Thank you for the contribution.

I'm going to keep the ticket open (#3) as, while helpful, your contribution wasn't really what I was needing in that regard - more a full-scale audit and unset of variables throughout SocketServer when they go out of use to ensure that memory stays reasonable while the server is running.

Again, though - I appreciate any and all assistance - Thanks! :D

**Comment by PeterPlucinski** [comment]
No problem, thanks. I might tackle the full scale audit and unset at some stage and get your thoughts (unless someone else does before me).

**Pull request merged**
